services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: banking_risk_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking_risk_streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
      - PYTHONUNBUFFERED=1
    depends_on:
      - api